sudo: false
language: python

python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install pipenv --upgrade
  - pipenv install --dev --skip-lock

script:
  - pipenv run py.test

cache:
  - pip

notifications:
email: false
